[logger]
level   = "INFO"
path    = "./sender.log"

[db]
inMemory    = false
host        = "localhost"
port        = 5432
username    = "postgres"
password    = "123456"
dbname      = "calendar"

[kafka]
Url          = "localhost:29092"
Group        = "calendar"
ConsumeTopic = "calendar-event-consumer"
ServiceName  = "calendar"